name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List changed files
        id: changes
        uses: tj-actions/changed-files@v44

      - name: Determine docs-only
        id: docs
        run: |
          docs_only=true
          for f in ${{ steps.changes.outputs.all_changed_files }}; do
            if [[ ! "$f" =~ \.md$ ]]; then
              docs_only=false
              break
            fi
          done
          echo "docs_only=$docs_only" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black flake8 pytest

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: npx markdownlint-cli '**/*.md'

      - name: Run black
        if: steps.docs.outputs.docs_only == 'false'
        run: black --check .

      - name: Run flake8
        if: steps.docs.outputs.docs_only == 'false'
        run: flake8 .

      - name: Run pytest
        if: steps.docs.outputs.docs_only == 'false'
        run: pytest -v

      - name: Check links
        run: npx markdown-link-check README.md
